name: practica1_flutter
description: "Practica 1 - Crea tu Pizza (Flutter)"
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    # (Opcional) Si luego pones imágenes en assets/images/
    # - assets/images/
